ALTER TABLE companies ADD COLUMN IF NOT EXISTS auto_spec BOOLEAN DEFAULT false;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS spec_max_concurrent INTEGER DEFAULT 2;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS spec_delay_minutes INTEGER DEFAULT 5;
